"""Add width and height columns to Photo

Revision ID: ff492cd1dc06
Revises: 593645151263
Create Date: 2025-04-29 19:49:46.968597

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff492cd1dc06"
down_revision: Union[str, None] = "593645151263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("photos", sa.Column("height", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "height")
    op.drop_column("photos", "width")
    # ### end Alembic commands ###
